name: release assets
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - run: make fmt
    - run: make tidy
    - run: make vet
    - run: make test-unit
    - run: make test-system
    - uses: goreleaser/goreleaser-action@v3
      with:
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
